version: '3.9'
services:
  api:
    build:
      context: .
      target: development
    env_file:
      - .env
    environment:
      MONGO_HOST: mongo
      REDIS_HOST: redis
    ports:
      - ${PORT}:3000
      - "9229:9229"
    networks:
      - web
    links:
      - redis
    command: npm run start:debug
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

  mongo:
    image: mongo:5
    command: mongod --port 27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - ${MONGO_PORT}:27017
    networks:
      - web
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  redis:
    image: redis:alpine
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - web
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

networks:
  web: